// Autogenerated from CSharpBinding.addin.xml

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("PlayScript Language Binding")]
[assembly: AssemblyDescription ("PlayScript Language Binding")]
[assembly: AssemblyVersion ("1.0")]
[assembly: AssemblyCopyright ("SushiHangover")]
[assembly: InternalsVisibleTo("UnitTests")]